### ISSUE TITLE
Worker is not building

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#419] opened 2019-06-06 17:08 UTC
Its actions are alternating between Move and Stop.

![image](https://user-images.githubusercontent.com/5833235/59051994-190a8780-885c-11e9-9629-b93fa76c861a.png)

**Comment by Unusual229** [comment] 2019-06-06 19:51
Most likely trying to build at (0, 0)
Without more info, it will be hard to fix.
Could add the building type next to the 'B', so its easier to debug such issues.

**Comment by RaphaelRoyerRivard** [comment] 2019-06-15 20:38
Happened once more, the building it wanted to build was a supply depot (later in the game, it was the only building left in the list and when the worker died, the supply depot was removed from the list).
![image](https://user-images.githubusercontent.com/5833235/59556097-0ba37a80-8f8b-11e9-83ba-c895088c6e30.png)

**Comment by Unusual229** [comment] 2019-06-17 14:21
A worker is trying to build at an invalid stop???

**Comment by RaphaelRoyerRivard** [comment] 2019-06-17 14:26
It's not the first time that I see it, so I'll describe what I've seen the other times, because I haven't seen the worker move in that specific game. Usually, the worker receives a move command just in front of it and a stop command right after, continuously. I'm not sure if this starts as soon as it is selected to build or if it happens only when it reaches the building location.

**Comment by Unusual229** [comment] 2019-06-17 14:52
If I have the map name, it should be easy to reproduce it (since there is no random in building placement).

**Comment by Unusual229** [comment] 2019-06-17 14:52
And if there is no change at all to the production manager, the building order matters.

**Comment by RaphaelRoyerRivard** [comment] 2019-06-17 14:56
Well, it was King's Cove, but it doesn't happen often.

**Comment by Unusual229** [comment] 2019-07-07 05:10
![image](https://user-images.githubusercontent.com/8284324/60764238-11edb980-a054-11e9-9e28-aa2d4645949a.png)

**Comment by Unusual229** [comment] 2019-07-07 05:11
There are some buildable tiles at the bottom of the l'edge, I think this is the issue.

**Comment by Unusual229** [comment] 2019-07-07 05:12
Might be possible to only add a height check.

**Comment by Unusual229** [comment] 2019-07-07 06:41
Ran a few games on that map, could not repro, but should be fixed.

**Closed by Unusual229** 2019-07-07 06:41 UTC
Labels: bug, macro
