### ISSUE TITLE
Sometimes no Starport is built

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#616] opened 2019-12-06 14:45 UTC
https://ai-arena.net/matches/5514/
There also was a worker in the mineral line that kept being selected. Maybe the bug has something to do with that.
![image](https://user-images.githubusercontent.com/5833235/70331363-4e912d00-180d-11ea-9919-750f9ea7997f.png)

**Comment by Unusual229** [comment] 2019-12-11 05:35
Possibly an invalid build location again. The issue is supposed to be fixed, however maybe there is still an edge case that wasn't caught.
This version does include the changes to the building placement right?

**Comment by RaphaelRoyerRivard** [comment] 2019-12-11 15:57
Yes, but not the repositionning.

**Comment by Unusual229** [comment] 2020-01-09 18:33
Should be fixed by the change to canBuildHere and buildable.

**Comment by Unusual229** [comment] 2020-02-13 04:44
No recent occurence. Closing.

**Closed by Unusual229** 2020-02-13 04:44 UTC
Labels: Keep an eye out, bug, macro
