### ISSUE TITLE
Proxy location is horrible on World of Sleepers LE

### ISSUE THREAD

**Issue by Unusual229** [RaphaelRoyerRivard/MicroMachine#716] opened 2020-01-25 22:24 UTC
The mineral wall causes the path for ground unit to be extremly long.

**Comment by RaphaelRoyerRivard** [comment] 2020-01-25 23:28
Duplicate of https://github.com/RaphaelRoyerRivard/MicroMachine/issues/633

**Closed by RaphaelRoyerRivard** 2020-01-25 23:28 UTC
Labels: bug, macro
