### ISSUE TITLE
SCVs should not repair their resource depot before it is low hp

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [RaphaelRoyerRivard/MicroMachine#241] opened 2019-01-11 20:31 UTC
This might have cost us the game against MadBot on the Probots tournament.

**Comment by RaphaelRoyerRivard** [comment] 2019-01-11 20:34
The repair threshold could be 50% on CC and Orbital but 90% on Planetary.

**Comment by Unusual229** [comment] 2019-02-17 07:07
Je pense c'est fix, avec le auto repair à 30%, on va le repair quand il est low et la repair station est rendu trop petite pour pogner les depots. À confirmer.

**Comment by Unusual229** [comment] 2019-03-13 15:00
Will close the issue since I can confirm we repair all buildings that get to low hp.

**Closed by Unusual229** 2019-03-13 15:00 UTC
Labels: Keep an eye out, enhancement, macro
